ALTER TABLE "Loan" ADD COLUMN IF NOT EXISTS "categoryId" INTEGER;
ALTER TABLE "Loan" ADD CONSTRAINT IF NOT EXISTS "Loan_categoryId_fkey"
  FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE SET NULL ON UPDATE CASCADE;
